# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # lint
      - run:
          name: Lint
          command: npm run -s lint

      # Typecheck
      - run:
          name: Typecheck
          command: npm run -s typecheck

      # build
      - run:
          name: Build
          command: npm run -s build

      # copy webxr assets
      - run:
          name: Copy WebXR assets
          command: cp -r ./node_modules/@webxr-input-profiles/assets/dist/profiles ./www/webxr-assets

      # Copy files over
      - run:
          name: Build archive
          command: npm pack && mv lba2remake-`node -p "require('./package.json').version"`.tgz /tmp/lba2remake.tgz

      # Store artifacts
      - store_artifacts:
          path: /tmp/lba2remake.tgz
